version: '3.8'

services:
  web:
    build: ./web
    container_name: web
    networks:
      - mynetwork

  proxy:
    build: ./proxy
    container_name: proxy
    ports:
      - "80:80"
    networks:
      - mynetwork
    depends_on:
      - web

networks:
  mynetwork:
    driver: bridge