Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "256"
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update && apt-get install -y nginx
    sudo apt install -y curl
  SHELL
  
  config.vm.define "proxy" do |proxy|
    proxy.vm.hostname = "www.example.test"
    proxy.vm.network "private_network", ip: "192.168.57.10"
    
    proxy.vm.provision "shell", inline: <<-SHELL
      sudo cp /vagrant/proxy_default/default /etc/nginx/sites-available/default
      sudo cp /vagrant/proxy_default/hosts /etc/hosts
    SHELL
  end
  
  config.vm.define "web" do |web|
    web.vm.hostname = "w1.example.test"
    web.vm.network "private_network", ip: "192.168.57.11"
    
    web.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update && apt-get install -y nginx
      sudo apt install -y curl
      sudo cp /vagrant/web_default/index.html /var/www/html/index.html
      sudo cp /vagrant/web_default/default /etc/nginx/sites-available/default
    SHELL
  end  
end